In [1]:
import pandas as pd

In [8]:
df = pd.read_json("data/linkedin_jobs.json")

In [12]:
# Load the JSON
df = pd.read_json("data/linkedin_jobs.json")

# Drop duplicate rows
df_unique = df.drop_duplicates()

# (Optional) Reset the index
df_unique.reset_index(drop=True, inplace=True)

# Preview
df_unique

,job_id,job_url,job_title,company_name,location,posted_time,applicants,description,Seniority level,Employment type,Job function,Industries
0,4199363919,https://in.linkedin.com/jobs/view/devops-engin...,DevOps Engineer,Infosys Finacle,"Bengaluru, Karnataka, India",3 weeks ago,39 applicants,About the job\nJob description\nWe are seeking...,Associate,Full-time,"Engineering, Information Technology, and Other","Software Development, Financial Services, and ..."
1,4205907479,https://in.linkedin.com/jobs/view/devops-engin...,DevOps Engineer,Persistent Systems,"Pune, Maharashtra, India",2 weeks ago,152 applicants,About Persistent\nWe are a trusted Digital Eng...,Entry level,Full-time,Engineering and Information Technology,IT Services and IT Consulting
2,4159283422,https://www.linkedin.com/jobs/view/devops-engi...,DevOps Engineer,stakefish,United States,2 months ago,159 applicants,"As our DevOps Engineer, you will be helping us...",Mid-Senior level,Full-time,Engineering,IT Services and IT Consulting
3,4150490838,https://www.linkedin.com/jobs/view/devops-engi...,DevOps Engineer,IT Minds LLC,"San Antonio, TX",2 months ago,62 applicants,"San Antonio, TX (Hybrid)\n12+ month contract \...",Entry level,Full-time,Engineering and Information Technology,IT Services and IT Consulting
4,4215304968,https://ca.linkedin.com/jobs/view/devops-engin...,DevOps Engineer,Aarorn Technologies Inc,"Toronto, Ontario, Canada",2 days ago,123 applicants,"Job Title: DevOps Engineer\nLocation: Toronto,...",Mid-Senior level,Contract,Engineering and Information Technology,IT Services and IT Consulting
...,...,...,...,...,...,...,...,...,...,...,...,...
142,4214785256,https://ca.linkedin.com/jobs/view/data-analyst...,"Data Analyst, Driver Earnings",Lyft,"Toronto, Ontario, Canada",12 hours ago,147 applicants,"At Lyft, our purpose is to serve and connect. ...",Not Applicable,Full-time,Information Technology,Ground Passenger Transportation
143,4200093026,https://ca.linkedin.com/jobs/view/associate-da...,Associate Data Analyst - Energy & Sustainabili...,Siemens,"Toronto, Ontario, Canada",2 weeks ago,Over 200 applicants,Change the future with us.\nBuild a brighter f...,Associate,Full-time,Engineering,Automation Machinery Manufacturing
144,4213592616,https://ca.linkedin.com/jobs/view/data-analyst...,"Data Analyst, Product Analytics",Thomson Reuters,"Toronto, Ontario, Canada",1 day ago,Over 200 applicants,Summary:\nAre you passionate about applying ad...,Associate,Full-time,Information Technology,"Financial Services, Legal Services, and IT Ser..."
145,4117383909,https://ca.linkedin.com/jobs/view/data-analyst...,Data Analyst,NMG Consulting,"Toronto, Ontario, Canada",3 weeks ago,Over 200 applicants,SUMMARY STATEMENT\nWe offer an exciting role w...,Entry level,Full-time,"Finance, Information Technology, and Research","Financial Services, Insurance, and Research Se..."
146,4211125209,https://ca.linkedin.com/jobs/view/insights-ana...,Insights Analyst,Dropbox,Canada,1 week ago,Over 200 applicants,Dropbox is a Virtual First company. For this r...,Not Applicable,Full-time,"Research, Analyst, and Information Technology","Software Development, IT Services and IT Consu..."